name: "Publish"

env:
  ADDON_NAME: libp2p-ws-proxy

on:
  push:
    branches:
      - main
      - deploy-actions

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and Push Image'
        run: |
          docker build libp2p-ws-proxy --build-arg BUILD_FROM="homeassistant/amd64-base:latest" --tag ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-amd64:latest
          docker push ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-amd64:latest
          docker build libp2p-ws-proxy --build-arg BUILD_FROM="homeassistant/armhf-base:latest" --tag ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-armhf:latest
          docker push ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-armhf:latest
          docker build libp2p-ws-proxy --build-arg BUILD_FROM="homeassistant/armv7-base:latest" --tag ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-armv7:latest
          docker push ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-armv7:latest
          docker build libp2p-ws-proxy --build-arg BUILD_FROM="homeassistant/i386-base:latest" --tag ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-i386:latest
          docker push ghcr.io/pinoutltd/${{ env.ADDON_NAME }}-i386:latest