name: "Publish"

on:
  push:
    branches:
      - main
      - deploy-actions

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build Inventory Image'
        run: |
          docker build libp2p-ws-proxy --build-arg BUILD_FROM="homeassistant/amd64-base:latest" --tag ghcr.io/PinoutLTD/libp2p-ws-proxy:latest
          docker push ghcr.io/PinoutLTD/libp2p-ws-proxy:latest
      # - name: Publish
      #   uses: home-assistant/builder@master
      #   with:
      #     args: |
      #       --all \
      #       --target libp2p-ws-proxy \
      #       --docker-hub user-name-or-space-name